api: Use promise params to avoid error
error TS2344: Type '{ __tag__: "GET"; __param_position__: "second"; __param_type__: RouteContext; }' does not satisfy the constraint 'ParamCheck<RouteContext>'.
  The types of '__param_type__.params' are incompatible between these types.
    Type '{ fileId: string; }' is missing the following properties from type 'Promise<any>': then, catch, finally, [Symbol.toStringTag]

 49       {
          ~
 50         __tag__: 'GET'
    ~~~~~~~~~~~~~~~~~~~~~~
...
 52         __param_type__: SecondArg<MaybeField<TEntry, 'GET'>>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 53       },
    ~~~~~~~

Signed-off-by: hoang1007 <hoangvuhuy1007@gmail.com>